name: Deploy Lambda with AWS CDK

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use the appropriate version for your app

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install aws-cdk-lib constructs  # Ensure AWS CDK Python packages are installed

      - name: Install Node.js and AWS CDK CLI
        run: |
          npm install -g aws-cdk

      - name: Deploy with CDK
        run: |
          cdk deploy --require-approval never --app "python3 TechDeckCDK/app.py"  # Specify Python app file
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
